Traceback (most recent call last):
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'crop'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/scratchi/KDSS/kdss_ml/pipepine.py", line 24, in run_experiment
    train, test, val =  train_val_test_split(data=preprocessed_data,
  File "/scratchi/KDSS/kdss_ml/src/crop_type_classification/featurize.py", line 12, in train_val_test_split
    data['stratify_comb'] = data.apply(lambda row:'-'.join(map(lambda x: row[x], stratify)), axis=1)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/frame.py", line 10347, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
  File "/scratchi/KDSS/kdss_ml/src/crop_type_classification/featurize.py", line 12, in <lambda>
    data['stratify_comb'] = data.apply(lambda row:'-'.join(map(lambda x: row[x], stratify)), axis=1)
  File "/scratchi/KDSS/kdss_ml/src/crop_type_classification/featurize.py", line 12, in <lambda>
    data['stratify_comb'] = data.apply(lambda row:'-'.join(map(lambda x: row[x], stratify)), axis=1)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/series.py", line 1111, in __getitem__
    return self._get_value(key)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/series.py", line 1227, in _get_value
    loc = self.index.get_loc(label)
  File "/home/users/krishnas/scratchi/KDSS/miniconda3/envs/kdss/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3809, in get_loc
    raise KeyError(key) from err
KeyError: 'crop'